name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Run build script
        env:
          PLATFORMS: "darwin/amd64,darwin/arm64,windows/amd64,windows/arm64,linux/amd64,linux/arm64"
        run: |
          bash ./build.sh

      - name: Generate hashes
        run: |
          cd ./build
          for f in $(find . -type f); do
            sha256sum $f | sudo tee -a hashes.txt
          done

      - name: Upload
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./build/prscd-amd64-darwin.tar.gz
            ./build/prscd-arm64-darwin.tar.gz
            ./build/prscd-amd64-windows.tar.gz
            ./build/prscd-arm64-windows.tar.gz
            ./build/prscd-amd64-linux.tar.gz
            ./build/prscd-arm64-linux.tar.gz
            ./build/hashes.txt
